# Generated by Django 3.2 on 2021-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTSMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(choices=[('RM', 'NamJoon'), ('jin', 'SeokJin'), ('Suga', 'Yoongi'), ('J-Hope', 'HoSeok'), ('jimin', 'Jimin'), ('V', 'Tae'), ('JungKook', 'JungKook')], default='jimin', max_length=8)),
                ('age', models.IntegerField()),
                ('GoodThingAboutHim', models.CharField(max_length=100)),
            ],
        ),
    ]
